// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v5/services/keyword_plan_service.proto

package com.google.ads.googleads.v5.services;

public interface GenerateForecastCurveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v5.services.GenerateForecastCurveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The resource name of the keyword plan to be forecasted.
   * </pre>
   *
   * <code>string keyword_plan = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The keywordPlan.
   */
  java.lang.String getKeywordPlan();
  /**
   * <pre>
   * Required. The resource name of the keyword plan to be forecasted.
   * </pre>
   *
   * <code>string keyword_plan = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for keywordPlan.
   */
  com.google.protobuf.ByteString
      getKeywordPlanBytes();
}
