// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v20/enums/policy_topic_entry_type.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v20.enums;

public interface PolicyTopicEntryTypeEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v20.enums.PolicyTopicEntryTypeEnum)
    com.google.protobuf.MessageOrBuilder {
}
