// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v19/enums/income_range_type.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v19.enums;

public final class IncomeRangeTypeProto {
  private IncomeRangeTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v19_enums_IncomeRangeTypeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v19_enums_IncomeRangeTypeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6google/ads/googleads/v19/enums/income_" +
      "range_type.proto\022\036google.ads.googleads.v" +
      "19.enums\"\203\002\n\023IncomeRangeTypeEnum\"\353\001\n\017Inc" +
      "omeRangeType\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UNKNOWN" +
      "\020\001\022\027\n\021INCOME_RANGE_0_50\020\261\220\037\022\030\n\022INCOME_RA" +
      "NGE_50_60\020\262\220\037\022\030\n\022INCOME_RANGE_60_70\020\263\220\037\022" +
      "\030\n\022INCOME_RANGE_70_80\020\264\220\037\022\030\n\022INCOME_RANG" +
      "E_80_90\020\265\220\037\022\030\n\022INCOME_RANGE_90_UP\020\266\220\037\022\037\n" +
      "\031INCOME_RANGE_UNDETERMINED\020\260\220\037B\356\001\n\"com.g" +
      "oogle.ads.googleads.v19.enumsB\024IncomeRan" +
      "geTypeProtoP\001ZCgoogle.golang.org/genprot" +
      "o/googleapis/ads/googleads/v19/enums;enu" +
      "ms\242\002\003GAA\252\002\036Google.Ads.GoogleAds.V19.Enum" +
      "s\312\002\036Google\\Ads\\GoogleAds\\V19\\Enums\352\002\"Goo" +
      "gle::Ads::GoogleAds::V19::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v19_enums_IncomeRangeTypeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v19_enums_IncomeRangeTypeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v19_enums_IncomeRangeTypeEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
