// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v19/enums/local_services_lead_survey_answer.proto

// Protobuf Java Version: 3.25.3
package com.google.ads.googleads.v19.enums;

public interface LocalServicesLeadSurveyAnswerEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v19.enums.LocalServicesLeadSurveyAnswerEnum)
    com.google.protobuf.MessageOrBuilder {
}
