// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v19/enums/product_category_level.proto

// Protobuf Java Version: 3.25.3
package com.google.ads.googleads.v19.enums;

public interface ProductCategoryLevelEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v19.enums.ProductCategoryLevelEnum)
    com.google.protobuf.MessageOrBuilder {
}
