// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v15/enums/app_store.proto

// Protobuf Java Version: 3.25.3
package com.google.ads.googleads.v15.enums;

public final class AppStoreProto {
  private AppStoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v15_enums_AppStoreEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v15_enums_AppStoreEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.google/ads/googleads/v15/enums/app_sto" +
      "re.proto\022\036google.ads.googleads.v15.enums" +
      "\"[\n\014AppStoreEnum\"K\n\010AppStore\022\017\n\013UNSPECIF" +
      "IED\020\000\022\013\n\007UNKNOWN\020\001\022\020\n\014APPLE_ITUNES\020\002\022\017\n\013" +
      "GOOGLE_PLAY\020\003B\347\001\n\"com.google.ads.googlea" +
      "ds.v15.enumsB\rAppStoreProtoP\001ZCgoogle.go" +
      "lang.org/genproto/googleapis/ads/googlea" +
      "ds/v15/enums;enums\242\002\003GAA\252\002\036Google.Ads.Go" +
      "ogleAds.V15.Enums\312\002\036Google\\Ads\\GoogleAds" +
      "\\V15\\Enums\352\002\"Google::Ads::GoogleAds::V15" +
      "::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v15_enums_AppStoreEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v15_enums_AppStoreEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v15_enums_AppStoreEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
