// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v21/common/audience_insights_attribute.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v21.common;

public interface UserListAttributeMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v21.common.UserListAttributeMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The user list type.
   * </pre>
   *
   * <code>.google.ads.googleads.v21.enums.UserListTypeEnum.UserListType user_list_type = 1;</code>
   * @return The enum numeric value on the wire for userListType.
   */
  int getUserListTypeValue();
  /**
   * <pre>
   * The user list type.
   * </pre>
   *
   * <code>.google.ads.googleads.v21.enums.UserListTypeEnum.UserListType user_list_type = 1;</code>
   * @return The userListType.
   */
  com.google.ads.googleads.v21.enums.UserListTypeEnum.UserListType getUserListType();
}
