// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v9/enums/listing_group_type.proto

package com.google.ads.googleads.v9.enums;

public interface ListingGroupTypeEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v9.enums.ListingGroupTypeEnum)
    com.google.protobuf.MessageOrBuilder {
}
