// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v3/common/ad_type_infos.proto

package com.google.ads.googleads.v3.common;

public interface VideoOutstreamAdInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v3.common.VideoOutstreamAdInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The headline of the ad.
   * </pre>
   *
   * <code>.google.protobuf.StringValue headline = 1;</code>
   * @return Whether the headline field is set.
   */
  boolean hasHeadline();
  /**
   * <pre>
   * The headline of the ad.
   * </pre>
   *
   * <code>.google.protobuf.StringValue headline = 1;</code>
   * @return The headline.
   */
  com.google.protobuf.StringValue getHeadline();
  /**
   * <pre>
   * The headline of the ad.
   * </pre>
   *
   * <code>.google.protobuf.StringValue headline = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getHeadlineOrBuilder();

  /**
   * <pre>
   * The description line.
   * </pre>
   *
   * <code>.google.protobuf.StringValue description = 2;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <pre>
   * The description line.
   * </pre>
   *
   * <code>.google.protobuf.StringValue description = 2;</code>
   * @return The description.
   */
  com.google.protobuf.StringValue getDescription();
  /**
   * <pre>
   * The description line.
   * </pre>
   *
   * <code>.google.protobuf.StringValue description = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder();
}
