// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/ads/googleads/v23/errors/conversion_custom_variable_error.proto
// Protobuf Java Version: 4.31.0

package com.google.ads.googleads.v23.errors;

@com.google.protobuf.Generated
public interface ConversionCustomVariableErrorEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v23.errors.ConversionCustomVariableErrorEnum)
    com.google.protobuf.MessageOrBuilder {
}
