// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v23/errors/distinct_error.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v23.errors;

public interface DistinctErrorEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v23.errors.DistinctErrorEnum)
    com.google.protobuf.MessageOrBuilder {
}
