// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v18/enums/asset_automation_type.proto

// Protobuf Java Version: 3.25.3
package com.google.ads.googleads.v18.enums;

public final class AssetAutomationTypeProto {
  private AssetAutomationTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v18_enums_AssetAutomationTypeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v18_enums_AssetAutomationTypeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:google/ads/googleads/v18/enums/asset_a" +
      "utomation_type.proto\022\036google.ads.googlea" +
      "ds.v18.enums\"\265\001\n\027AssetAutomationTypeEnum" +
      "\"\231\001\n\023AssetAutomationType\022\017\n\013UNSPECIFIED\020" +
      "\000\022\013\n\007UNKNOWN\020\001\022\031\n\025TEXT_ASSET_AUTOMATION\020" +
      "\002\022$\n GENERATE_VERTICAL_YOUTUBE_VIDEOS\020\003\022" +
      "#\n\037GENERATE_SHORTER_YOUTUBE_VIDEOS\020\004B\362\001\n" +
      "\"com.google.ads.googleads.v18.enumsB\030Ass" +
      "etAutomationTypeProtoP\001ZCgoogle.golang.o" +
      "rg/genproto/googleapis/ads/googleads/v18" +
      "/enums;enums\242\002\003GAA\252\002\036Google.Ads.GoogleAd" +
      "s.V18.Enums\312\002\036Google\\Ads\\GoogleAds\\V18\\E" +
      "nums\352\002\"Google::Ads::GoogleAds::V18::Enum" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v18_enums_AssetAutomationTypeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v18_enums_AssetAutomationTypeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v18_enums_AssetAutomationTypeEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
