// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v18/enums/matching_function_operator.proto

// Protobuf Java Version: 3.25.3
package com.google.ads.googleads.v18.enums;

public final class MatchingFunctionOperatorProto {
  private MatchingFunctionOperatorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v18_enums_MatchingFunctionOperatorEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v18_enums_MatchingFunctionOperatorEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?google/ads/googleads/v18/enums/matchin" +
      "g_function_operator.proto\022\036google.ads.go" +
      "ogleads.v18.enums\"\225\001\n\034MatchingFunctionOp" +
      "eratorEnum\"u\n\030MatchingFunctionOperator\022\017" +
      "\n\013UNSPECIFIED\020\000\022\013\n\007UNKNOWN\020\001\022\006\n\002IN\020\002\022\014\n\010" +
      "IDENTITY\020\003\022\n\n\006EQUALS\020\004\022\007\n\003AND\020\005\022\020\n\014CONTA" +
      "INS_ANY\020\006B\367\001\n\"com.google.ads.googleads.v" +
      "18.enumsB\035MatchingFunctionOperatorProtoP" +
      "\001ZCgoogle.golang.org/genproto/googleapis" +
      "/ads/googleads/v18/enums;enums\242\002\003GAA\252\002\036G" +
      "oogle.Ads.GoogleAds.V18.Enums\312\002\036Google\\A" +
      "ds\\GoogleAds\\V18\\Enums\352\002\"Google::Ads::Go" +
      "ogleAds::V18::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v18_enums_MatchingFunctionOperatorEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v18_enums_MatchingFunctionOperatorEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v18_enums_MatchingFunctionOperatorEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
