// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v3/enums/tracking_code_page_format.proto

package com.google.ads.googleads.v3.enums;

public final class TrackingCodePageFormatProto {
  private TrackingCodePageFormatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v3_enums_TrackingCodePageFormatEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v3_enums_TrackingCodePageFormatEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=google/ads/googleads/v3/enums/tracking" +
      "_code_page_format.proto\022\035google.ads.goog" +
      "leads.v3.enums\032\034google/api/annotations.p" +
      "roto\"g\n\032TrackingCodePageFormatEnum\"I\n\026Tr" +
      "ackingCodePageFormat\022\017\n\013UNSPECIFIED\020\000\022\013\n" +
      "\007UNKNOWN\020\001\022\010\n\004HTML\020\002\022\007\n\003AMP\020\003B\360\001\n!com.go" +
      "ogle.ads.googleads.v3.enumsB\033TrackingCod" +
      "ePageFormatProtoP\001ZBgoogle.golang.org/ge" +
      "nproto/googleapis/ads/googleads/v3/enums" +
      ";enums\242\002\003GAA\252\002\035Google.Ads.GoogleAds.V3.E" +
      "nums\312\002\035Google\\Ads\\GoogleAds\\V3\\Enums\352\002!G" +
      "oogle::Ads::GoogleAds::V3::Enumsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_google_ads_googleads_v3_enums_TrackingCodePageFormatEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v3_enums_TrackingCodePageFormatEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v3_enums_TrackingCodePageFormatEnum_descriptor,
        new java.lang.String[] { });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
