// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v14/errors/image_error.proto

// Protobuf Java Version: 3.25.2
package com.google.ads.googleads.v14.errors;

public interface ImageErrorEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v14.errors.ImageErrorEnum)
    com.google.protobuf.MessageOrBuilder {
}
