// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v18/errors/asset_group_asset_error.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v18.errors;

public interface AssetGroupAssetErrorEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v18.errors.AssetGroupAssetErrorEnum)
    com.google.protobuf.MessageOrBuilder {
}
