// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v9/resources/third_party_app_analytics_link.proto

package com.google.ads.googleads.v9.resources;

public final class ThirdPartyAppAnalyticsLinkProto {
  private ThirdPartyAppAnalyticsLinkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v9_resources_ThirdPartyAppAnalyticsLink_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v9_resources_ThirdPartyAppAnalyticsLink_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nFgoogle/ads/googleads/v9/resources/thir" +
      "d_party_app_analytics_link.proto\022!google" +
      ".ads.googleads.v9.resources\032\037google/api/" +
      "field_behavior.proto\032\031google/api/resourc" +
      "e.proto\032\034google/api/annotations.proto\"\256\002" +
      "\n\032ThirdPartyAppAnalyticsLink\022R\n\rresource" +
      "_name\030\001 \001(\tB;\340A\005\372A5\n3googleads.googleapi" +
      "s.com/ThirdPartyAppAnalyticsLink\022#\n\021shar" +
      "eable_link_id\030\003 \001(\tB\003\340A\003H\000\210\001\001:\200\001\352A}\n3goo" +
      "gleads.googleapis.com/ThirdPartyAppAnaly" +
      "ticsLink\022Fcustomers/{customer_id}/thirdP" +
      "artyAppAnalyticsLinks/{customer_link_id}" +
      "B\024\n\022_shareable_link_idB\214\002\n%com.google.ad" +
      "s.googleads.v9.resourcesB\037ThirdPartyAppA" +
      "nalyticsLinkProtoP\001ZJgoogle.golang.org/g" +
      "enproto/googleapis/ads/googleads/v9/reso" +
      "urces;resources\242\002\003GAA\252\002!Google.Ads.Googl" +
      "eAds.V9.Resources\312\002!Google\\Ads\\GoogleAds" +
      "\\V9\\Resources\352\002%Google::Ads::GoogleAds::" +
      "V9::Resourcesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v9_resources_ThirdPartyAppAnalyticsLink_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v9_resources_ThirdPartyAppAnalyticsLink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v9_resources_ThirdPartyAppAnalyticsLink_descriptor,
        new java.lang.String[] { "ResourceName", "ShareableLinkId", "ShareableLinkId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
