// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v10/enums/served_asset_field_type.proto

package com.google.ads.googleads.v10.enums;

public final class ServedAssetFieldTypeProto {
  private ServedAssetFieldTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v10_enums_ServedAssetFieldTypeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v10_enums_ServedAssetFieldTypeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<google/ads/googleads/v10/enums/served_" +
      "asset_field_type.proto\022\036google.ads.googl" +
      "eads.v10.enums\"\247\001\n\030ServedAssetFieldTypeE" +
      "num\"\212\001\n\024ServedAssetFieldType\022\017\n\013UNSPECIF" +
      "IED\020\000\022\013\n\007UNKNOWN\020\001\022\016\n\nHEADLINE_1\020\002\022\016\n\nHE" +
      "ADLINE_2\020\003\022\016\n\nHEADLINE_3\020\004\022\021\n\rDESCRIPTIO" +
      "N_1\020\005\022\021\n\rDESCRIPTION_2\020\006B\363\001\n\"com.google." +
      "ads.googleads.v10.enumsB\031ServedAssetFiel" +
      "dTypeProtoP\001ZCgoogle.golang.org/genproto" +
      "/googleapis/ads/googleads/v10/enums;enum" +
      "s\242\002\003GAA\252\002\036Google.Ads.GoogleAds.V10.Enums" +
      "\312\002\036Google\\Ads\\GoogleAds\\V10\\Enums\352\002\"Goog" +
      "le::Ads::GoogleAds::V10::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v10_enums_ServedAssetFieldTypeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v10_enums_ServedAssetFieldTypeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v10_enums_ServedAssetFieldTypeEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
