// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v10/enums/sk_ad_network_user_type.proto

package com.google.ads.googleads.v10.enums;

public final class SkAdNetworkUserTypeProto {
  private SkAdNetworkUserTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v10_enums_SkAdNetworkUserTypeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v10_enums_SkAdNetworkUserTypeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<google/ads/googleads/v10/enums/sk_ad_n" +
      "etwork_user_type.proto\022\036google.ads.googl" +
      "eads.v10.enums\032\034google/api/annotations.p" +
      "roto\"\203\001\n\027SkAdNetworkUserTypeEnum\"h\n\023SkAd" +
      "NetworkUserType\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UNKN" +
      "OWN\020\001\022\017\n\013UNAVAILABLE\020\002\022\021\n\rNEW_INSTALLER\020" +
      "\003\022\017\n\013REINSTALLER\020\004B\362\001\n\"com.google.ads.go" +
      "ogleads.v10.enumsB\030SkAdNetworkUserTypePr" +
      "otoP\001ZCgoogle.golang.org/genproto/google" +
      "apis/ads/googleads/v10/enums;enums\242\002\003GAA" +
      "\252\002\036Google.Ads.GoogleAds.V10.Enums\312\002\036Goog" +
      "le\\Ads\\GoogleAds\\V10\\Enums\352\002\"Google::Ads" +
      "::GoogleAds::V10::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v10_enums_SkAdNetworkUserTypeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v10_enums_SkAdNetworkUserTypeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v10_enums_SkAdNetworkUserTypeEnum_descriptor,
        new java.lang.String[] { });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
