// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v7/errors/feed_item_set_link_error.proto

package com.google.ads.googleads.v7.errors;

public final class FeedItemSetLinkErrorProto {
  private FeedItemSetLinkErrorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v7_errors_FeedItemSetLinkErrorEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v7_errors_FeedItemSetLinkErrorEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=google/ads/googleads/v7/errors/feed_it" +
      "em_set_link_error.proto\022\036google.ads.goog" +
      "leads.v7.errors\032\034google/api/annotations." +
      "proto\"\215\001\n\030FeedItemSetLinkErrorEnum\"q\n\024Fe" +
      "edItemSetLinkError\022\017\n\013UNSPECIFIED\020\000\022\013\n\007U" +
      "NKNOWN\020\001\022\024\n\020FEED_ID_MISMATCH\020\002\022%\n!NO_MUT" +
      "ATE_ALLOWED_FOR_DYNAMIC_SET\020\003B\364\001\n\"com.go" +
      "ogle.ads.googleads.v7.errorsB\031FeedItemSe" +
      "tLinkErrorProtoP\001ZDgoogle.golang.org/gen" +
      "proto/googleapis/ads/googleads/v7/errors" +
      ";errors\242\002\003GAA\252\002\036Google.Ads.GoogleAds.V7." +
      "Errors\312\002\036Google\\Ads\\GoogleAds\\V7\\Errors\352" +
      "\002\"Google::Ads::GoogleAds::V7::Errorsb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v7_errors_FeedItemSetLinkErrorEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v7_errors_FeedItemSetLinkErrorEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v7_errors_FeedItemSetLinkErrorEnum_descriptor,
        new java.lang.String[] { });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
