// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v2/resources/ad_group_ad.proto

package com.google.ads.googleads.v2.resources;

public final class AdGroupAdProto {
  private AdGroupAdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v2_resources_AdGroupAd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v2_resources_AdGroupAd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v2_resources_AdGroupAdPolicySummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v2_resources_AdGroupAdPolicySummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3google/ads/googleads/v2/resources/ad_g" +
      "roup_ad.proto\022!google.ads.googleads.v2.r" +
      "esources\032+google/ads/googleads/v2/common" +
      "/policy.proto\0326google/ads/googleads/v2/e" +
      "nums/ad_group_ad_status.proto\032/google/ad" +
      "s/googleads/v2/enums/ad_strength.proto\032:" +
      "google/ads/googleads/v2/enums/policy_app" +
      "roval_status.proto\0328google/ads/googleads" +
      "/v2/enums/policy_review_status.proto\032*go" +
      "ogle/ads/googleads/v2/resources/ad.proto" +
      "\032\036google/protobuf/wrappers.proto\032\034google" +
      "/api/annotations.proto\"\373\002\n\tAdGroupAd\022\025\n\r" +
      "resource_name\030\001 \001(\t\022R\n\006status\030\003 \001(\0162B.go" +
      "ogle.ads.googleads.v2.enums.AdGroupAdSta" +
      "tusEnum.AdGroupAdStatus\022.\n\010ad_group\030\004 \001(" +
      "\0132\034.google.protobuf.StringValue\0221\n\002ad\030\005 " +
      "\001(\0132%.google.ads.googleads.v2.resources." +
      "Ad\022Q\n\016policy_summary\030\006 \001(\01329.google.ads." +
      "googleads.v2.resources.AdGroupAdPolicySu" +
      "mmary\022M\n\013ad_strength\030\007 \001(\01628.google.ads." +
      "googleads.v2.enums.AdStrengthEnum.AdStre" +
      "ngth\"\260\002\n\026AdGroupAdPolicySummary\022N\n\024polic" +
      "y_topic_entries\030\001 \003(\01320.google.ads.googl" +
      "eads.v2.common.PolicyTopicEntry\022_\n\rrevie" +
      "w_status\030\002 \001(\0162H.google.ads.googleads.v2" +
      ".enums.PolicyReviewStatusEnum.PolicyRevi" +
      "ewStatus\022e\n\017approval_status\030\003 \001(\0162L.goog" +
      "le.ads.googleads.v2.enums.PolicyApproval" +
      "StatusEnum.PolicyApprovalStatusB\373\001\n%com." +
      "google.ads.googleads.v2.resourcesB\016AdGro" +
      "upAdProtoP\001ZJgoogle.golang.org/genproto/" +
      "googleapis/ads/googleads/v2/resources;re" +
      "sources\242\002\003GAA\252\002!Google.Ads.GoogleAds.V2." +
      "Resources\312\002!Google\\Ads\\GoogleAds\\V2\\Reso" +
      "urces\352\002%Google::Ads::GoogleAds::V2::Reso" +
      "urcesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ads.googleads.v2.common.PolicyProto.getDescriptor(),
          com.google.ads.googleads.v2.enums.AdGroupAdStatusProto.getDescriptor(),
          com.google.ads.googleads.v2.enums.AdStrengthProto.getDescriptor(),
          com.google.ads.googleads.v2.enums.PolicyApprovalStatusProto.getDescriptor(),
          com.google.ads.googleads.v2.enums.PolicyReviewStatusProto.getDescriptor(),
          com.google.ads.googleads.v2.resources.AdProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_google_ads_googleads_v2_resources_AdGroupAd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v2_resources_AdGroupAd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v2_resources_AdGroupAd_descriptor,
        new java.lang.String[] { "ResourceName", "Status", "AdGroup", "Ad", "PolicySummary", "AdStrength", });
    internal_static_google_ads_googleads_v2_resources_AdGroupAdPolicySummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ads_googleads_v2_resources_AdGroupAdPolicySummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v2_resources_AdGroupAdPolicySummary_descriptor,
        new java.lang.String[] { "PolicyTopicEntries", "ReviewStatus", "ApprovalStatus", });
    com.google.ads.googleads.v2.common.PolicyProto.getDescriptor();
    com.google.ads.googleads.v2.enums.AdGroupAdStatusProto.getDescriptor();
    com.google.ads.googleads.v2.enums.AdStrengthProto.getDescriptor();
    com.google.ads.googleads.v2.enums.PolicyApprovalStatusProto.getDescriptor();
    com.google.ads.googleads.v2.enums.PolicyReviewStatusProto.getDescriptor();
    com.google.ads.googleads.v2.resources.AdProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
