// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v15/errors/reach_plan_error.proto

// Protobuf Java Version: 3.25.2
package com.google.ads.googleads.v15.errors;

public final class ReachPlanErrorProto {
  private ReachPlanErrorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v15_errors_ReachPlanErrorEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v15_errors_ReachPlanErrorEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6google/ads/googleads/v15/errors/reach_" +
      "plan_error.proto\022\037google.ads.googleads.v" +
      "15.errors\"\275\001\n\022ReachPlanErrorEnum\"\246\001\n\016Rea" +
      "chPlanError\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UNKNOWN\020" +
      "\001\022!\n\035NOT_FORECASTABLE_MISSING_RATE\020\002\022)\n%" +
      "NOT_FORECASTABLE_NOT_ENOUGH_INVENTORY\020\003\022" +
      "(\n$NOT_FORECASTABLE_ACCOUNT_NOT_ENABLED\020" +
      "\004B\363\001\n#com.google.ads.googleads.v15.error" +
      "sB\023ReachPlanErrorProtoP\001ZEgoogle.golang." +
      "org/genproto/googleapis/ads/googleads/v1" +
      "5/errors;errors\242\002\003GAA\252\002\037Google.Ads.Googl" +
      "eAds.V15.Errors\312\002\037Google\\Ads\\GoogleAds\\V" +
      "15\\Errors\352\002#Google::Ads::GoogleAds::V15:" +
      ":Errorsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v15_errors_ReachPlanErrorEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v15_errors_ReachPlanErrorEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v15_errors_ReachPlanErrorEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
