// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v21/enums/local_services_business_registration_type.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v21.enums;

public interface LocalServicesBusinessRegistrationTypeEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v21.enums.LocalServicesBusinessRegistrationTypeEnum)
    com.google.protobuf.MessageOrBuilder {
}
