// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v21/enums/third_party_reach_integration_partner.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v21.enums;

public interface ThirdPartyReachIntegrationPartnerEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v21.enums.ThirdPartyReachIntegrationPartnerEnum)
    com.google.protobuf.MessageOrBuilder {
}
