// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v21/enums/user_list_customer_type_category.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v21.enums;

public final class UserListCustomerTypeCategoryProto {
  private UserListCustomerTypeCategoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v21_enums_UserListCustomerTypeCategoryEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v21_enums_UserListCustomerTypeCategoryEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEgoogle/ads/googleads/v21/enums/user_li" +
      "st_customer_type_category.proto\022\036google." +
      "ads.googleads.v21.enums\"\347\003\n UserListCust" +
      "omerTypeCategoryEnum\"\302\003\n\034UserListCustome" +
      "rTypeCategory\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UNKNOW" +
      "N\020\001\022\021\n\rALL_CUSTOMERS\020\002\022\016\n\nPURCHASERS\020\003\022\030" +
      "\n\024HIGH_VALUE_CUSTOMERS\020\004\022\030\n\024DISENGAGED_C" +
      "USTOMERS\020\005\022\023\n\017QUALIFIED_LEADS\020\006\022\023\n\017CONVE" +
      "RTED_LEADS\020\007\022\024\n\020PAID_SUBSCRIBERS\020\010\022\024\n\020LO" +
      "YALTY_SIGN_UPS\020\t\022\023\n\017CART_ABANDONERS\020\n\022\032\n" +
      "\026LOYALTY_TIER_1_MEMBERS\020\013\022\032\n\026LOYALTY_TIE" +
      "R_2_MEMBERS\020\014\022\032\n\026LOYALTY_TIER_3_MEMBERS\020" +
      "\r\022\032\n\026LOYALTY_TIER_4_MEMBERS\020\016\022\032\n\026LOYALTY" +
      "_TIER_5_MEMBERS\020\017\022\032\n\026LOYALTY_TIER_6_MEMB" +
      "ERS\020\020\022\032\n\026LOYALTY_TIER_7_MEMBERS\020\021B\373\001\n\"co" +
      "m.google.ads.googleads.v21.enumsB!UserLi" +
      "stCustomerTypeCategoryProtoP\001ZCgoogle.go" +
      "lang.org/genproto/googleapis/ads/googlea" +
      "ds/v21/enums;enums\242\002\003GAA\252\002\036Google.Ads.Go" +
      "ogleAds.V21.Enums\312\002\036Google\\Ads\\GoogleAds" +
      "\\V21\\Enums\352\002\"Google::Ads::GoogleAds::V21" +
      "::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v21_enums_UserListCustomerTypeCategoryEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v21_enums_UserListCustomerTypeCategoryEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v21_enums_UserListCustomerTypeCategoryEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
