// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v12/resources/invoice.proto

package com.google.ads.googleads.v12.resources;

public final class InvoiceProto {
  private InvoiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v12_resources_Invoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v12_resources_Invoice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v12_resources_Invoice_AccountSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v12_resources_Invoice_AccountSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v12_resources_Invoice_AccountBudgetSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v12_resources_Invoice_AccountBudgetSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0google/ads/googleads/v12/resources/inv" +
      "oice.proto\022\"google.ads.googleads.v12.res" +
      "ources\032+google/ads/googleads/v12/common/" +
      "dates.proto\0321google/ads/googleads/v12/en" +
      "ums/invoice_type.proto\032\037google/api/field" +
      "_behavior.proto\032\031google/api/resource.pro" +
      "to\"\303\036\n\007Invoice\022@\n\rresource_name\030\001 \001(\tB)\342" +
      "A\001\003\372A\"\n googleads.googleapis.com/Invoice" +
      "\022\025\n\002id\030\031 \001(\tB\004\342A\001\003H\000\210\001\001\022O\n\004type\030\003 \001(\0162;." +
      "google.ads.googleads.v12.enums.InvoiceTy" +
      "peEnum.InvoiceTypeB\004\342A\001\003\022 \n\rbilling_setu" +
      "p\030\032 \001(\tB\004\342A\001\003H\001\210\001\001\022&\n\023payments_account_i" +
      "d\030\033 \001(\tB\004\342A\001\003H\002\210\001\001\022&\n\023payments_profile_i" +
      "d\030\034 \001(\tB\004\342A\001\003H\003\210\001\001\022\035\n\nissue_date\030\035 \001(\tB\004" +
      "\342A\001\003H\004\210\001\001\022\033\n\010due_date\030\036 \001(\tB\004\342A\001\003H\005\210\001\001\022L" +
      "\n\022service_date_range\030\t \001(\0132*.google.ads." +
      "googleads.v12.common.DateRangeB\004\342A\001\003\022 \n\r" +
      "currency_code\030\037 \001(\tB\004\342A\001\003H\006\210\001\001\0220\n\"adjust" +
      "ments_subtotal_amount_micros\030\023 \001(\003B\004\342A\001\003" +
      "\022+\n\035adjustments_tax_amount_micros\030\024 \001(\003B" +
      "\004\342A\001\003\022-\n\037adjustments_total_amount_micros" +
      "\030\025 \001(\003B\004\342A\001\003\0225\n\'regulatory_costs_subtota" +
      "l_amount_micros\030\026 \001(\003B\004\342A\001\003\0220\n\"regulator" +
      "y_costs_tax_amount_micros\030\027 \001(\003B\004\342A\001\003\0222\n" +
      "$regulatory_costs_total_amount_micros\030\030 " +
      "\001(\003B\004\342A\001\003\022)\n\026subtotal_amount_micros\030! \001(" +
      "\003B\004\342A\001\003H\007\210\001\001\022$\n\021tax_amount_micros\030\" \001(\003B" +
      "\004\342A\001\003H\010\210\001\001\022&\n\023total_amount_micros\030# \001(\003B" +
      "\004\342A\001\003H\t\210\001\001\022$\n\021corrected_invoice\030$ \001(\tB\004\342" +
      "A\001\003H\n\210\001\001\022\037\n\021replaced_invoices\030% \003(\tB\004\342A\001" +
      "\003\022\032\n\007pdf_url\030& \001(\tB\004\342A\001\003H\013\210\001\001\022h\n\030account" +
      "_budget_summaries\030\022 \003(\0132@.google.ads.goo" +
      "gleads.v12.resources.Invoice.AccountBudg" +
      "etSummaryB\004\342A\001\003\022[\n\021account_summaries\030\' \003" +
      "(\0132:.google.ads.googleads.v12.resources." +
      "Invoice.AccountSummaryB\004\342A\001\003\032\336\013\n\016Account" +
      "Summary\022\033\n\010customer\030\001 \001(\tB\004\342A\001\003H\000\210\001\001\022<\n)" +
      "billing_correction_subtotal_amount_micro" +
      "s\030\002 \001(\003B\004\342A\001\003H\001\210\001\001\0227\n$billing_correction" +
      "_tax_amount_micros\030\003 \001(\003B\004\342A\001\003H\002\210\001\001\0229\n&b" +
      "illing_correction_total_amount_micros\030\004 " +
      "\001(\003B\004\342A\001\003H\003\210\001\001\022;\n(coupon_adjustment_subt" +
      "otal_amount_micros\030\005 \001(\003B\004\342A\001\003H\004\210\001\001\0226\n#c" +
      "oupon_adjustment_tax_amount_micros\030\006 \001(\003" +
      "B\004\342A\001\003H\005\210\001\001\0228\n%coupon_adjustment_total_a" +
      "mount_micros\030\007 \001(\003B\004\342A\001\003H\006\210\001\001\022B\n/excess_" +
      "credit_adjustment_subtotal_amount_micros" +
      "\030\010 \001(\003B\004\342A\001\003H\007\210\001\001\022=\n*excess_credit_adjus" +
      "tment_tax_amount_micros\030\t \001(\003B\004\342A\001\003H\010\210\001\001" +
      "\022?\n,excess_credit_adjustment_total_amoun" +
      "t_micros\030\n \001(\003B\004\342A\001\003H\t\210\001\001\022:\n\'regulatory_" +
      "costs_subtotal_amount_micros\030\013 \001(\003B\004\342A\001\003" +
      "H\n\210\001\001\0225\n\"regulatory_costs_tax_amount_mic" +
      "ros\030\014 \001(\003B\004\342A\001\003H\013\210\001\001\0227\n$regulatory_costs" +
      "_total_amount_micros\030\r \001(\003B\004\342A\001\003H\014\210\001\001\022)\n" +
      "\026subtotal_amount_micros\030\016 \001(\003B\004\342A\001\003H\r\210\001\001" +
      "\022$\n\021tax_amount_micros\030\017 \001(\003B\004\342A\001\003H\016\210\001\001\022&" +
      "\n\023total_amount_micros\030\020 \001(\003B\004\342A\001\003H\017\210\001\001B\013" +
      "\n\t_customerB,\n*_billing_correction_subto" +
      "tal_amount_microsB\'\n%_billing_correction" +
      "_tax_amount_microsB)\n\'_billing_correctio" +
      "n_total_amount_microsB+\n)_coupon_adjustm" +
      "ent_subtotal_amount_microsB&\n$_coupon_ad" +
      "justment_tax_amount_microsB(\n&_coupon_ad" +
      "justment_total_amount_microsB2\n0_excess_" +
      "credit_adjustment_subtotal_amount_micros" +
      "B-\n+_excess_credit_adjustment_tax_amount" +
      "_microsB/\n-_excess_credit_adjustment_tot" +
      "al_amount_microsB*\n(_regulatory_costs_su" +
      "btotal_amount_microsB%\n#_regulatory_cost" +
      "s_tax_amount_microsB\'\n%_regulatory_costs" +
      "_total_amount_microsB\031\n\027_subtotal_amount" +
      "_microsB\024\n\022_tax_amount_microsB\026\n\024_total_" +
      "amount_micros\032\210\007\n\024AccountBudgetSummary\022\033" +
      "\n\010customer\030\n \001(\tB\004\342A\001\003H\000\210\001\001\022,\n\031customer_" +
      "descriptive_name\030\013 \001(\tB\004\342A\001\003H\001\210\001\001\022!\n\016acc" +
      "ount_budget\030\014 \001(\tB\004\342A\001\003H\002\210\001\001\022&\n\023account_" +
      "budget_name\030\r \001(\tB\004\342A\001\003H\003\210\001\001\022(\n\025purchase" +
      "_order_number\030\016 \001(\tB\004\342A\001\003H\004\210\001\001\022)\n\026subtot" +
      "al_amount_micros\030\017 \001(\003B\004\342A\001\003H\005\210\001\001\022$\n\021tax" +
      "_amount_micros\030\020 \001(\003B\004\342A\001\003H\006\210\001\001\022&\n\023total" +
      "_amount_micros\030\021 \001(\003B\004\342A\001\003H\007\210\001\001\022V\n\034billa" +
      "ble_activity_date_range\030\t \001(\0132*.google.a" +
      "ds.googleads.v12.common.DateRangeB\004\342A\001\003\022" +
      "\'\n\024served_amount_micros\030\022 \001(\003B\004\342A\001\003H\010\210\001\001" +
      "\022\'\n\024billed_amount_micros\030\023 \001(\003B\004\342A\001\003H\t\210\001" +
      "\001\022-\n\032overdelivery_amount_micros\030\024 \001(\003B\004\342" +
      "A\001\003H\n\210\001\001\0221\n\036invalid_activity_amount_micr" +
      "os\030\025 \001(\003B\004\342A\001\003H\013\210\001\001B\013\n\t_customerB\034\n\032_cus" +
      "tomer_descriptive_nameB\021\n\017_account_budge" +
      "tB\026\n\024_account_budget_nameB\030\n\026_purchase_o" +
      "rder_numberB\031\n\027_subtotal_amount_microsB\024" +
      "\n\022_tax_amount_microsB\026\n\024_total_amount_mi" +
      "crosB\027\n\025_served_amount_microsB\027\n\025_billed" +
      "_amount_microsB\035\n\033_overdelivery_amount_m" +
      "icrosB!\n\037_invalid_activity_amount_micros" +
      ":T\352AQ\n googleads.googleapis.com/Invoice\022" +
      "-customers/{customer_id}/invoices/{invoi" +
      "ce_id}B\005\n\003_idB\020\n\016_billing_setupB\026\n\024_paym" +
      "ents_account_idB\026\n\024_payments_profile_idB" +
      "\r\n\013_issue_dateB\013\n\t_due_dateB\020\n\016_currency" +
      "_codeB\031\n\027_subtotal_amount_microsB\024\n\022_tax" +
      "_amount_microsB\026\n\024_total_amount_microsB\024" +
      "\n\022_corrected_invoiceB\n\n\010_pdf_urlB\376\001\n&com" +
      ".google.ads.googleads.v12.resourcesB\014Inv" +
      "oiceProtoP\001ZKgoogle.golang.org/genproto/" +
      "googleapis/ads/googleads/v12/resources;r" +
      "esources\242\002\003GAA\252\002\"Google.Ads.GoogleAds.V1" +
      "2.Resources\312\002\"Google\\Ads\\GoogleAds\\V12\\R" +
      "esources\352\002&Google::Ads::GoogleAds::V12::" +
      "Resourcesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ads.googleads.v12.common.DatesProto.getDescriptor(),
          com.google.ads.googleads.v12.enums.InvoiceTypeProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v12_resources_Invoice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v12_resources_Invoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v12_resources_Invoice_descriptor,
        new java.lang.String[] { "ResourceName", "Id", "Type", "BillingSetup", "PaymentsAccountId", "PaymentsProfileId", "IssueDate", "DueDate", "ServiceDateRange", "CurrencyCode", "AdjustmentsSubtotalAmountMicros", "AdjustmentsTaxAmountMicros", "AdjustmentsTotalAmountMicros", "RegulatoryCostsSubtotalAmountMicros", "RegulatoryCostsTaxAmountMicros", "RegulatoryCostsTotalAmountMicros", "SubtotalAmountMicros", "TaxAmountMicros", "TotalAmountMicros", "CorrectedInvoice", "ReplacedInvoices", "PdfUrl", "AccountBudgetSummaries", "AccountSummaries", "Id", "BillingSetup", "PaymentsAccountId", "PaymentsProfileId", "IssueDate", "DueDate", "CurrencyCode", "SubtotalAmountMicros", "TaxAmountMicros", "TotalAmountMicros", "CorrectedInvoice", "PdfUrl", });
    internal_static_google_ads_googleads_v12_resources_Invoice_AccountSummary_descriptor =
      internal_static_google_ads_googleads_v12_resources_Invoice_descriptor.getNestedTypes().get(0);
    internal_static_google_ads_googleads_v12_resources_Invoice_AccountSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v12_resources_Invoice_AccountSummary_descriptor,
        new java.lang.String[] { "Customer", "BillingCorrectionSubtotalAmountMicros", "BillingCorrectionTaxAmountMicros", "BillingCorrectionTotalAmountMicros", "CouponAdjustmentSubtotalAmountMicros", "CouponAdjustmentTaxAmountMicros", "CouponAdjustmentTotalAmountMicros", "ExcessCreditAdjustmentSubtotalAmountMicros", "ExcessCreditAdjustmentTaxAmountMicros", "ExcessCreditAdjustmentTotalAmountMicros", "RegulatoryCostsSubtotalAmountMicros", "RegulatoryCostsTaxAmountMicros", "RegulatoryCostsTotalAmountMicros", "SubtotalAmountMicros", "TaxAmountMicros", "TotalAmountMicros", "Customer", "BillingCorrectionSubtotalAmountMicros", "BillingCorrectionTaxAmountMicros", "BillingCorrectionTotalAmountMicros", "CouponAdjustmentSubtotalAmountMicros", "CouponAdjustmentTaxAmountMicros", "CouponAdjustmentTotalAmountMicros", "ExcessCreditAdjustmentSubtotalAmountMicros", "ExcessCreditAdjustmentTaxAmountMicros", "ExcessCreditAdjustmentTotalAmountMicros", "RegulatoryCostsSubtotalAmountMicros", "RegulatoryCostsTaxAmountMicros", "RegulatoryCostsTotalAmountMicros", "SubtotalAmountMicros", "TaxAmountMicros", "TotalAmountMicros", });
    internal_static_google_ads_googleads_v12_resources_Invoice_AccountBudgetSummary_descriptor =
      internal_static_google_ads_googleads_v12_resources_Invoice_descriptor.getNestedTypes().get(1);
    internal_static_google_ads_googleads_v12_resources_Invoice_AccountBudgetSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v12_resources_Invoice_AccountBudgetSummary_descriptor,
        new java.lang.String[] { "Customer", "CustomerDescriptiveName", "AccountBudget", "AccountBudgetName", "PurchaseOrderNumber", "SubtotalAmountMicros", "TaxAmountMicros", "TotalAmountMicros", "BillableActivityDateRange", "ServedAmountMicros", "BilledAmountMicros", "OverdeliveryAmountMicros", "InvalidActivityAmountMicros", "Customer", "CustomerDescriptiveName", "AccountBudget", "AccountBudgetName", "PurchaseOrderNumber", "SubtotalAmountMicros", "TaxAmountMicros", "TotalAmountMicros", "ServedAmountMicros", "BilledAmountMicros", "OverdeliveryAmountMicros", "InvalidActivityAmountMicros", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.ads.googleads.v12.common.DatesProto.getDescriptor();
    com.google.ads.googleads.v12.enums.InvoiceTypeProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
