// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v1/services/mutate_job_service.proto

package com.google.ads.googleads.v1.services;

/**
 * <pre>
 * Request message for [MutateJobService.AddMutateJobOperations][google.ads.googleads.v1.services.MutateJobService.AddMutateJobOperations]
 * </pre>
 *
 * Protobuf type {@code google.ads.googleads.v1.services.AddMutateJobOperationsRequest}
 */
public  final class AddMutateJobOperationsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.ads.googleads.v1.services.AddMutateJobOperationsRequest)
    AddMutateJobOperationsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddMutateJobOperationsRequest.newBuilder() to construct.
  private AddMutateJobOperationsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddMutateJobOperationsRequest() {
    resourceName_ = "";
    sequenceToken_ = "";
    mutateOperations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddMutateJobOperationsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            resourceName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            sequenceToken_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              mutateOperations_ = new java.util.ArrayList<com.google.ads.googleads.v1.services.MutateOperation>();
              mutable_bitField0_ |= 0x00000004;
            }
            mutateOperations_.add(
                input.readMessage(com.google.ads.googleads.v1.services.MutateOperation.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        mutateOperations_ = java.util.Collections.unmodifiableList(mutateOperations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.ads.googleads.v1.services.MutateJobServiceProto.internal_static_google_ads_googleads_v1_services_AddMutateJobOperationsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.ads.googleads.v1.services.MutateJobServiceProto.internal_static_google_ads_googleads_v1_services_AddMutateJobOperationsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.class, com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object resourceName_;
  /**
   * <pre>
   * The resource name of the MutateJob.
   * </pre>
   *
   * <code>string resource_name = 1;</code>
   */
  public java.lang.String getResourceName() {
    java.lang.Object ref = resourceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The resource name of the MutateJob.
   * </pre>
   *
   * <code>string resource_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResourceNameBytes() {
    java.lang.Object ref = resourceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQUENCE_TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object sequenceToken_;
  /**
   * <pre>
   * A token used to enforce sequencing.
   * The first AddMutateJobOperations request for a MutateJob should not set
   * sequence_token. Subsequent requests must set sequence_token to the value of
   * next_sequence_token received in the previous AddMutateJobOperations
   * response.
   * </pre>
   *
   * <code>string sequence_token = 2;</code>
   */
  public java.lang.String getSequenceToken() {
    java.lang.Object ref = sequenceToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sequenceToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A token used to enforce sequencing.
   * The first AddMutateJobOperations request for a MutateJob should not set
   * sequence_token. Subsequent requests must set sequence_token to the value of
   * next_sequence_token received in the previous AddMutateJobOperations
   * response.
   * </pre>
   *
   * <code>string sequence_token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSequenceTokenBytes() {
    java.lang.Object ref = sequenceToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sequenceToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MUTATE_OPERATIONS_FIELD_NUMBER = 3;
  private java.util.List<com.google.ads.googleads.v1.services.MutateOperation> mutateOperations_;
  /**
   * <pre>
   * The list of mutates being added.
   * Operations can use negative integers as temp ids to signify dependencies
   * between entities created in this MutateJob. For example, a customer with
   * id = 1234 can create a campaign and an ad group in that same campaign by
   * creating a campaign in the first operation with the resource name
   * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
   * in the second operation with the campaign field also set to
   * "customers/1234/campaigns/-1".
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
   */
  public java.util.List<com.google.ads.googleads.v1.services.MutateOperation> getMutateOperationsList() {
    return mutateOperations_;
  }
  /**
   * <pre>
   * The list of mutates being added.
   * Operations can use negative integers as temp ids to signify dependencies
   * between entities created in this MutateJob. For example, a customer with
   * id = 1234 can create a campaign and an ad group in that same campaign by
   * creating a campaign in the first operation with the resource name
   * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
   * in the second operation with the campaign field also set to
   * "customers/1234/campaigns/-1".
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
   */
  public java.util.List<? extends com.google.ads.googleads.v1.services.MutateOperationOrBuilder> 
      getMutateOperationsOrBuilderList() {
    return mutateOperations_;
  }
  /**
   * <pre>
   * The list of mutates being added.
   * Operations can use negative integers as temp ids to signify dependencies
   * between entities created in this MutateJob. For example, a customer with
   * id = 1234 can create a campaign and an ad group in that same campaign by
   * creating a campaign in the first operation with the resource name
   * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
   * in the second operation with the campaign field also set to
   * "customers/1234/campaigns/-1".
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
   */
  public int getMutateOperationsCount() {
    return mutateOperations_.size();
  }
  /**
   * <pre>
   * The list of mutates being added.
   * Operations can use negative integers as temp ids to signify dependencies
   * between entities created in this MutateJob. For example, a customer with
   * id = 1234 can create a campaign and an ad group in that same campaign by
   * creating a campaign in the first operation with the resource name
   * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
   * in the second operation with the campaign field also set to
   * "customers/1234/campaigns/-1".
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
   */
  public com.google.ads.googleads.v1.services.MutateOperation getMutateOperations(int index) {
    return mutateOperations_.get(index);
  }
  /**
   * <pre>
   * The list of mutates being added.
   * Operations can use negative integers as temp ids to signify dependencies
   * between entities created in this MutateJob. For example, a customer with
   * id = 1234 can create a campaign and an ad group in that same campaign by
   * creating a campaign in the first operation with the resource name
   * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
   * in the second operation with the campaign field also set to
   * "customers/1234/campaigns/-1".
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
   */
  public com.google.ads.googleads.v1.services.MutateOperationOrBuilder getMutateOperationsOrBuilder(
      int index) {
    return mutateOperations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getResourceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceName_);
    }
    if (!getSequenceTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sequenceToken_);
    }
    for (int i = 0; i < mutateOperations_.size(); i++) {
      output.writeMessage(3, mutateOperations_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getResourceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceName_);
    }
    if (!getSequenceTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sequenceToken_);
    }
    for (int i = 0; i < mutateOperations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, mutateOperations_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest)) {
      return super.equals(obj);
    }
    com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest other = (com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest) obj;

    if (!getResourceName()
        .equals(other.getResourceName())) return false;
    if (!getSequenceToken()
        .equals(other.getSequenceToken())) return false;
    if (!getMutateOperationsList()
        .equals(other.getMutateOperationsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESOURCE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getResourceName().hashCode();
    hash = (37 * hash) + SEQUENCE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getSequenceToken().hashCode();
    if (getMutateOperationsCount() > 0) {
      hash = (37 * hash) + MUTATE_OPERATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMutateOperationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for [MutateJobService.AddMutateJobOperations][google.ads.googleads.v1.services.MutateJobService.AddMutateJobOperations]
   * </pre>
   *
   * Protobuf type {@code google.ads.googleads.v1.services.AddMutateJobOperationsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.ads.googleads.v1.services.AddMutateJobOperationsRequest)
      com.google.ads.googleads.v1.services.AddMutateJobOperationsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.ads.googleads.v1.services.MutateJobServiceProto.internal_static_google_ads_googleads_v1_services_AddMutateJobOperationsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.ads.googleads.v1.services.MutateJobServiceProto.internal_static_google_ads_googleads_v1_services_AddMutateJobOperationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.class, com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.Builder.class);
    }

    // Construct using com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMutateOperationsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resourceName_ = "";

      sequenceToken_ = "";

      if (mutateOperationsBuilder_ == null) {
        mutateOperations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        mutateOperationsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.ads.googleads.v1.services.MutateJobServiceProto.internal_static_google_ads_googleads_v1_services_AddMutateJobOperationsRequest_descriptor;
    }

    @java.lang.Override
    public com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest getDefaultInstanceForType() {
      return com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest build() {
      com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest buildPartial() {
      com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest result = new com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.resourceName_ = resourceName_;
      result.sequenceToken_ = sequenceToken_;
      if (mutateOperationsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          mutateOperations_ = java.util.Collections.unmodifiableList(mutateOperations_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.mutateOperations_ = mutateOperations_;
      } else {
        result.mutateOperations_ = mutateOperationsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest) {
        return mergeFrom((com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest other) {
      if (other == com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest.getDefaultInstance()) return this;
      if (!other.getResourceName().isEmpty()) {
        resourceName_ = other.resourceName_;
        onChanged();
      }
      if (!other.getSequenceToken().isEmpty()) {
        sequenceToken_ = other.sequenceToken_;
        onChanged();
      }
      if (mutateOperationsBuilder_ == null) {
        if (!other.mutateOperations_.isEmpty()) {
          if (mutateOperations_.isEmpty()) {
            mutateOperations_ = other.mutateOperations_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMutateOperationsIsMutable();
            mutateOperations_.addAll(other.mutateOperations_);
          }
          onChanged();
        }
      } else {
        if (!other.mutateOperations_.isEmpty()) {
          if (mutateOperationsBuilder_.isEmpty()) {
            mutateOperationsBuilder_.dispose();
            mutateOperationsBuilder_ = null;
            mutateOperations_ = other.mutateOperations_;
            bitField0_ = (bitField0_ & ~0x00000004);
            mutateOperationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMutateOperationsFieldBuilder() : null;
          } else {
            mutateOperationsBuilder_.addAllMessages(other.mutateOperations_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object resourceName_ = "";
    /**
     * <pre>
     * The resource name of the MutateJob.
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public java.lang.String getResourceName() {
      java.lang.Object ref = resourceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The resource name of the MutateJob.
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      java.lang.Object ref = resourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The resource name of the MutateJob.
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public Builder setResourceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource name of the MutateJob.
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public Builder clearResourceName() {
      
      resourceName_ = getDefaultInstance().getResourceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource name of the MutateJob.
     * </pre>
     *
     * <code>string resource_name = 1;</code>
     */
    public Builder setResourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sequenceToken_ = "";
    /**
     * <pre>
     * A token used to enforce sequencing.
     * The first AddMutateJobOperations request for a MutateJob should not set
     * sequence_token. Subsequent requests must set sequence_token to the value of
     * next_sequence_token received in the previous AddMutateJobOperations
     * response.
     * </pre>
     *
     * <code>string sequence_token = 2;</code>
     */
    public java.lang.String getSequenceToken() {
      java.lang.Object ref = sequenceToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sequenceToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A token used to enforce sequencing.
     * The first AddMutateJobOperations request for a MutateJob should not set
     * sequence_token. Subsequent requests must set sequence_token to the value of
     * next_sequence_token received in the previous AddMutateJobOperations
     * response.
     * </pre>
     *
     * <code>string sequence_token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSequenceTokenBytes() {
      java.lang.Object ref = sequenceToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sequenceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A token used to enforce sequencing.
     * The first AddMutateJobOperations request for a MutateJob should not set
     * sequence_token. Subsequent requests must set sequence_token to the value of
     * next_sequence_token received in the previous AddMutateJobOperations
     * response.
     * </pre>
     *
     * <code>string sequence_token = 2;</code>
     */
    public Builder setSequenceToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sequenceToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A token used to enforce sequencing.
     * The first AddMutateJobOperations request for a MutateJob should not set
     * sequence_token. Subsequent requests must set sequence_token to the value of
     * next_sequence_token received in the previous AddMutateJobOperations
     * response.
     * </pre>
     *
     * <code>string sequence_token = 2;</code>
     */
    public Builder clearSequenceToken() {
      
      sequenceToken_ = getDefaultInstance().getSequenceToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A token used to enforce sequencing.
     * The first AddMutateJobOperations request for a MutateJob should not set
     * sequence_token. Subsequent requests must set sequence_token to the value of
     * next_sequence_token received in the previous AddMutateJobOperations
     * response.
     * </pre>
     *
     * <code>string sequence_token = 2;</code>
     */
    public Builder setSequenceTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sequenceToken_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.ads.googleads.v1.services.MutateOperation> mutateOperations_ =
      java.util.Collections.emptyList();
    private void ensureMutateOperationsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        mutateOperations_ = new java.util.ArrayList<com.google.ads.googleads.v1.services.MutateOperation>(mutateOperations_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ads.googleads.v1.services.MutateOperation, com.google.ads.googleads.v1.services.MutateOperation.Builder, com.google.ads.googleads.v1.services.MutateOperationOrBuilder> mutateOperationsBuilder_;

    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public java.util.List<com.google.ads.googleads.v1.services.MutateOperation> getMutateOperationsList() {
      if (mutateOperationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mutateOperations_);
      } else {
        return mutateOperationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public int getMutateOperationsCount() {
      if (mutateOperationsBuilder_ == null) {
        return mutateOperations_.size();
      } else {
        return mutateOperationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public com.google.ads.googleads.v1.services.MutateOperation getMutateOperations(int index) {
      if (mutateOperationsBuilder_ == null) {
        return mutateOperations_.get(index);
      } else {
        return mutateOperationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder setMutateOperations(
        int index, com.google.ads.googleads.v1.services.MutateOperation value) {
      if (mutateOperationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMutateOperationsIsMutable();
        mutateOperations_.set(index, value);
        onChanged();
      } else {
        mutateOperationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder setMutateOperations(
        int index, com.google.ads.googleads.v1.services.MutateOperation.Builder builderForValue) {
      if (mutateOperationsBuilder_ == null) {
        ensureMutateOperationsIsMutable();
        mutateOperations_.set(index, builderForValue.build());
        onChanged();
      } else {
        mutateOperationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder addMutateOperations(com.google.ads.googleads.v1.services.MutateOperation value) {
      if (mutateOperationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMutateOperationsIsMutable();
        mutateOperations_.add(value);
        onChanged();
      } else {
        mutateOperationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder addMutateOperations(
        int index, com.google.ads.googleads.v1.services.MutateOperation value) {
      if (mutateOperationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMutateOperationsIsMutable();
        mutateOperations_.add(index, value);
        onChanged();
      } else {
        mutateOperationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder addMutateOperations(
        com.google.ads.googleads.v1.services.MutateOperation.Builder builderForValue) {
      if (mutateOperationsBuilder_ == null) {
        ensureMutateOperationsIsMutable();
        mutateOperations_.add(builderForValue.build());
        onChanged();
      } else {
        mutateOperationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder addMutateOperations(
        int index, com.google.ads.googleads.v1.services.MutateOperation.Builder builderForValue) {
      if (mutateOperationsBuilder_ == null) {
        ensureMutateOperationsIsMutable();
        mutateOperations_.add(index, builderForValue.build());
        onChanged();
      } else {
        mutateOperationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder addAllMutateOperations(
        java.lang.Iterable<? extends com.google.ads.googleads.v1.services.MutateOperation> values) {
      if (mutateOperationsBuilder_ == null) {
        ensureMutateOperationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mutateOperations_);
        onChanged();
      } else {
        mutateOperationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder clearMutateOperations() {
      if (mutateOperationsBuilder_ == null) {
        mutateOperations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        mutateOperationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public Builder removeMutateOperations(int index) {
      if (mutateOperationsBuilder_ == null) {
        ensureMutateOperationsIsMutable();
        mutateOperations_.remove(index);
        onChanged();
      } else {
        mutateOperationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public com.google.ads.googleads.v1.services.MutateOperation.Builder getMutateOperationsBuilder(
        int index) {
      return getMutateOperationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public com.google.ads.googleads.v1.services.MutateOperationOrBuilder getMutateOperationsOrBuilder(
        int index) {
      if (mutateOperationsBuilder_ == null) {
        return mutateOperations_.get(index);  } else {
        return mutateOperationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public java.util.List<? extends com.google.ads.googleads.v1.services.MutateOperationOrBuilder> 
         getMutateOperationsOrBuilderList() {
      if (mutateOperationsBuilder_ != null) {
        return mutateOperationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mutateOperations_);
      }
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public com.google.ads.googleads.v1.services.MutateOperation.Builder addMutateOperationsBuilder() {
      return getMutateOperationsFieldBuilder().addBuilder(
          com.google.ads.googleads.v1.services.MutateOperation.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public com.google.ads.googleads.v1.services.MutateOperation.Builder addMutateOperationsBuilder(
        int index) {
      return getMutateOperationsFieldBuilder().addBuilder(
          index, com.google.ads.googleads.v1.services.MutateOperation.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of mutates being added.
     * Operations can use negative integers as temp ids to signify dependencies
     * between entities created in this MutateJob. For example, a customer with
     * id = 1234 can create a campaign and an ad group in that same campaign by
     * creating a campaign in the first operation with the resource name
     * explicitly set to "customers/1234/campaigns/-1", and creating an ad group
     * in the second operation with the campaign field also set to
     * "customers/1234/campaigns/-1".
     * </pre>
     *
     * <code>repeated .google.ads.googleads.v1.services.MutateOperation mutate_operations = 3;</code>
     */
    public java.util.List<com.google.ads.googleads.v1.services.MutateOperation.Builder> 
         getMutateOperationsBuilderList() {
      return getMutateOperationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.ads.googleads.v1.services.MutateOperation, com.google.ads.googleads.v1.services.MutateOperation.Builder, com.google.ads.googleads.v1.services.MutateOperationOrBuilder> 
        getMutateOperationsFieldBuilder() {
      if (mutateOperationsBuilder_ == null) {
        mutateOperationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.ads.googleads.v1.services.MutateOperation, com.google.ads.googleads.v1.services.MutateOperation.Builder, com.google.ads.googleads.v1.services.MutateOperationOrBuilder>(
                mutateOperations_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        mutateOperations_ = null;
      }
      return mutateOperationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.ads.googleads.v1.services.AddMutateJobOperationsRequest)
  }

  // @@protoc_insertion_point(class_scope:google.ads.googleads.v1.services.AddMutateJobOperationsRequest)
  private static final com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest();
  }

  public static com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddMutateJobOperationsRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddMutateJobOperationsRequest>() {
    @java.lang.Override
    public AddMutateJobOperationsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddMutateJobOperationsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddMutateJobOperationsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddMutateJobOperationsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.ads.googleads.v1.services.AddMutateJobOperationsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

