// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/ads/googleads/v25/enums/multi_party_auth_review_target_resource.proto
// Protobuf Java Version: 4.31.0

package com.google.ads.googleads.v25.enums;

@com.google.protobuf.Generated
public final class MultiPartyAuthReviewTargetResourceProto {
  private MultiPartyAuthReviewTargetResourceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      MultiPartyAuthReviewTargetResourceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v25_enums_MultiPartyAuthReviewTargetResourceEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_ads_googleads_v25_enums_MultiPartyAuthReviewTargetResourceEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nLgoogle/ads/googleads/v25/enums/multi_p" +
      "arty_auth_review_target_resource.proto\022\036" +
      "google.ads.googleads.v25.enums\"\254\001\n&Multi" +
      "PartyAuthReviewTargetResourceEnum\"\201\001\n\"Mu" +
      "ltiPartyAuthReviewTargetResource\022\017\n\013UNSP" +
      "ECIFIED\020\000\022\013\n\007UNKNOWN\020\001\022\030\n\024CUSTOMER_USER_" +
      "ACCESS\020\002\022#\n\037CUSTOMER_USER_ACCESS_INVITAT" +
      "ION\020\003B\201\002\n\"com.google.ads.googleads.v25.e" +
      "numsB\'MultiPartyAuthReviewTargetResource" +
      "ProtoP\001ZCgoogle.golang.org/genproto/goog" +
      "leapis/ads/googleads/v25/enums;enums\242\002\003G" +
      "AA\252\002\036Google.Ads.GoogleAds.V25.Enums\312\002\036Go" +
      "ogle\\Ads\\GoogleAds\\V25\\Enums\352\002\"Google::A" +
      "ds::GoogleAds::V25::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_ads_googleads_v25_enums_MultiPartyAuthReviewTargetResourceEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v25_enums_MultiPartyAuthReviewTargetResourceEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_ads_googleads_v25_enums_MultiPartyAuthReviewTargetResourceEnum_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
