// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v14/resources/asset_group_listing_group_filter.proto

package com.google.ads.googleads.v14.resources;

public final class AssetGroupListingGroupFilterProto {
  private AssetGroupListingGroupFilterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_AssetGroupListingGroupFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_AssetGroupListingGroupFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimensionPath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimensionPath_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBiddingCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBiddingCategory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBrand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBrand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCondition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCondition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCustomAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCustomAttribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductItemId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductItemId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nIgoogle/ads/googleads/v14/resources/ass" +
      "et_group_listing_group_filter.proto\022\"goo" +
      "gle.ads.googleads.v14.resources\032Pgoogle/" +
      "ads/googleads/v14/enums/listing_group_fi" +
      "lter_bidding_category_level.proto\032Pgoogl" +
      "e/ads/googleads/v14/enums/listing_group_" +
      "filter_custom_attribute_index.proto\032Igoo" +
      "gle/ads/googleads/v14/enums/listing_grou" +
      "p_filter_product_channel.proto\032Kgoogle/a" +
      "ds/googleads/v14/enums/listing_group_fil" +
      "ter_product_condition.proto\032Lgoogle/ads/" +
      "googleads/v14/enums/listing_group_filter" +
      "_product_type_level.proto\032Cgoogle/ads/go" +
      "ogleads/v14/enums/listing_group_filter_t" +
      "ype_enum.proto\032Bgoogle/ads/googleads/v14" +
      "/enums/listing_group_filter_vertical.pro" +
      "to\032\037google/api/field_behavior.proto\032\031goo" +
      "gle/api/resource.proto\"\327\006\n\034AssetGroupLis" +
      "tingGroupFilter\022U\n\rresource_name\030\001 \001(\tB>" +
      "\342A\001\005\372A7\n5googleads.googleapis.com/AssetG" +
      "roupListingGroupFilter\022A\n\013asset_group\030\002 " +
      "\001(\tB,\342A\001\005\372A%\n#googleads.googleapis.com/A" +
      "ssetGroup\022\020\n\002id\030\003 \001(\003B\004\342A\001\003\022e\n\004type\030\004 \001(" +
      "\0162Q.google.ads.googleads.v14.enums.Listi" +
      "ngGroupFilterTypeEnum.ListingGroupFilter" +
      "TypeB\004\342A\001\005\022q\n\010vertical\030\005 \001(\0162Y.google.ad" +
      "s.googleads.v14.enums.ListingGroupFilter" +
      "VerticalEnum.ListingGroupFilterVerticalB" +
      "\004\342A\001\005\022S\n\ncase_value\030\006 \001(\0132?.google.ads.g" +
      "oogleads.v14.resources.ListingGroupFilte" +
      "rDimension\022c\n\033parent_listing_group_filte" +
      "r\030\007 \001(\tB>\342A\001\005\372A7\n5googleads.googleapis.c" +
      "om/AssetGroupListingGroupFilter\022W\n\004path\030" +
      "\010 \001(\0132C.google.ads.googleads.v14.resourc" +
      "es.ListingGroupFilterDimensionPathB\004\342A\001\003" +
      ":\235\001\352A\231\001\n5googleads.googleapis.com/AssetG" +
      "roupListingGroupFilter\022`customers/{custo" +
      "mer_id}/assetGroupListingGroupFilters/{a" +
      "sset_group_id}~{listing_group_filter_id}" +
      "\"|\n\037ListingGroupFilterDimensionPath\022Y\n\nd" +
      "imensions\030\001 \003(\0132?.google.ads.googleads.v" +
      "14.resources.ListingGroupFilterDimension" +
      "B\004\342A\001\003\"\307\r\n\033ListingGroupFilterDimension\022z" +
      "\n\030product_bidding_category\030\001 \001(\0132V.googl" +
      "e.ads.googleads.v14.resources.ListingGro" +
      "upFilterDimension.ProductBiddingCategory" +
      "H\000\022e\n\rproduct_brand\030\002 \001(\0132L.google.ads.g" +
      "oogleads.v14.resources.ListingGroupFilte" +
      "rDimension.ProductBrandH\000\022i\n\017product_cha" +
      "nnel\030\003 \001(\0132N.google.ads.googleads.v14.re" +
      "sources.ListingGroupFilterDimension.Prod" +
      "uctChannelH\000\022m\n\021product_condition\030\004 \001(\0132" +
      "P.google.ads.googleads.v14.resources.Lis" +
      "tingGroupFilterDimension.ProductConditio" +
      "nH\000\022z\n\030product_custom_attribute\030\005 \001(\0132V." +
      "google.ads.googleads.v14.resources.Listi" +
      "ngGroupFilterDimension.ProductCustomAttr" +
      "ibuteH\000\022h\n\017product_item_id\030\006 \001(\0132M.googl" +
      "e.ads.googleads.v14.resources.ListingGro" +
      "upFilterDimension.ProductItemIdH\000\022c\n\014pro" +
      "duct_type\030\007 \001(\0132K.google.ads.googleads.v" +
      "14.resources.ListingGroupFilterDimension" +
      ".ProductTypeH\000\032\263\001\n\026ProductBiddingCategor" +
      "y\022\017\n\002id\030\001 \001(\003H\000\210\001\001\022\200\001\n\005level\030\002 \001(\0162q.goo" +
      "gle.ads.googleads.v14.enums.ListingGroup" +
      "FilterBiddingCategoryLevelEnum.ListingGr" +
      "oupFilterBiddingCategoryLevelB\005\n\003_id\032,\n\014" +
      "ProductBrand\022\022\n\005value\030\001 \001(\tH\000\210\001\001B\010\n\006_val" +
      "ue\032\210\001\n\016ProductChannel\022v\n\007channel\030\001 \001(\0162e" +
      ".google.ads.googleads.v14.enums.ListingG" +
      "roupFilterProductChannelEnum.ListingGrou" +
      "pFilterProductChannel\032\220\001\n\020ProductConditi" +
      "on\022|\n\tcondition\030\001 \001(\0162i.google.ads.googl" +
      "eads.v14.enums.ListingGroupFilterProduct" +
      "ConditionEnum.ListingGroupFilterProductC" +
      "ondition\032\271\001\n\026ProductCustomAttribute\022\022\n\005v" +
      "alue\030\001 \001(\tH\000\210\001\001\022\200\001\n\005index\030\002 \001(\0162q.google" +
      ".ads.googleads.v14.enums.ListingGroupFil" +
      "terCustomAttributeIndexEnum.ListingGroup" +
      "FilterCustomAttributeIndexB\010\n\006_value\032-\n\r" +
      "ProductItemId\022\022\n\005value\030\001 \001(\tH\000\210\001\001B\010\n\006_va" +
      "lue\032\245\001\n\013ProductType\022\022\n\005value\030\001 \001(\tH\000\210\001\001\022" +
      "x\n\005level\030\002 \001(\0162i.google.ads.googleads.v1" +
      "4.enums.ListingGroupFilterProductTypeLev" +
      "elEnum.ListingGroupFilterProductTypeLeve" +
      "lB\010\n\006_valueB\013\n\tdimensionB\223\002\n&com.google." +
      "ads.googleads.v14.resourcesB!AssetGroupL" +
      "istingGroupFilterProtoP\001ZKgoogle.golang." +
      "org/genproto/googleapis/ads/googleads/v1" +
      "4/resources;resources\242\002\003GAA\252\002\"Google.Ads" +
      ".GoogleAds.V14.Resources\312\002\"Google\\Ads\\Go" +
      "ogleAds\\V14\\Resources\352\002&Google::Ads::Goo" +
      "gleAds::V14::Resourcesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ads.googleads.v14.enums.ListingGroupFilterBiddingCategoryLevelProto.getDescriptor(),
          com.google.ads.googleads.v14.enums.ListingGroupFilterCustomAttributeIndexProto.getDescriptor(),
          com.google.ads.googleads.v14.enums.ListingGroupFilterProductChannelProto.getDescriptor(),
          com.google.ads.googleads.v14.enums.ListingGroupFilterProductConditionProto.getDescriptor(),
          com.google.ads.googleads.v14.enums.ListingGroupFilterProductTypeLevelProto.getDescriptor(),
          com.google.ads.googleads.v14.enums.ListingGroupFilterTypeEnumProto.getDescriptor(),
          com.google.ads.googleads.v14.enums.ListingGroupFilterVerticalProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v14_resources_AssetGroupListingGroupFilter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v14_resources_AssetGroupListingGroupFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_AssetGroupListingGroupFilter_descriptor,
        new java.lang.String[] { "ResourceName", "AssetGroup", "Id", "Type", "Vertical", "CaseValue", "ParentListingGroupFilter", "Path", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimensionPath_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimensionPath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimensionPath_descriptor,
        new java.lang.String[] { "Dimensions", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor,
        new java.lang.String[] { "ProductBiddingCategory", "ProductBrand", "ProductChannel", "ProductCondition", "ProductCustomAttribute", "ProductItemId", "ProductType", "Dimension", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBiddingCategory_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(0);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBiddingCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBiddingCategory_descriptor,
        new java.lang.String[] { "Id", "Level", "Id", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBrand_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(1);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBrand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductBrand_descriptor,
        new java.lang.String[] { "Value", "Value", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductChannel_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(2);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductChannel_descriptor,
        new java.lang.String[] { "Channel", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCondition_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(3);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCondition_descriptor,
        new java.lang.String[] { "Condition", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCustomAttribute_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(4);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCustomAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductCustomAttribute_descriptor,
        new java.lang.String[] { "Value", "Index", "Value", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductItemId_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(5);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductItemId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductItemId_descriptor,
        new java.lang.String[] { "Value", "Value", });
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductType_descriptor =
      internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_descriptor.getNestedTypes().get(6);
    internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v14_resources_ListingGroupFilterDimension_ProductType_descriptor,
        new java.lang.String[] { "Value", "Level", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.ads.googleads.v14.enums.ListingGroupFilterBiddingCategoryLevelProto.getDescriptor();
    com.google.ads.googleads.v14.enums.ListingGroupFilterCustomAttributeIndexProto.getDescriptor();
    com.google.ads.googleads.v14.enums.ListingGroupFilterProductChannelProto.getDescriptor();
    com.google.ads.googleads.v14.enums.ListingGroupFilterProductConditionProto.getDescriptor();
    com.google.ads.googleads.v14.enums.ListingGroupFilterProductTypeLevelProto.getDescriptor();
    com.google.ads.googleads.v14.enums.ListingGroupFilterTypeEnumProto.getDescriptor();
    com.google.ads.googleads.v14.enums.ListingGroupFilterVerticalProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
