// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v5/enums/criterion_type.proto

package com.google.ads.googleads.v5.enums;

public interface CriterionTypeEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v5.enums.CriterionTypeEnum)
    com.google.protobuf.MessageOrBuilder {
}
