// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v5/enums/optimization_goal_type.proto

package com.google.ads.googleads.v5.enums;

public final class OptimizationGoalTypeProto {
  private OptimizationGoalTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v5_enums_OptimizationGoalTypeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v5_enums_OptimizationGoalTypeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:google/ads/googleads/v5/enums/optimiza" +
      "tion_goal_type.proto\022\035google.ads.googlea" +
      "ds.v5.enums\032\034google/api/annotations.prot" +
      "o\"y\n\030OptimizationGoalTypeEnum\"]\n\024Optimiz" +
      "ationGoalType\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UNKNOW" +
      "N\020\001\022\017\n\013CALL_CLICKS\020\002\022\026\n\022DRIVING_DIRECTIO" +
      "NS\020\003B\356\001\n!com.google.ads.googleads.v5.enu" +
      "msB\031OptimizationGoalTypeProtoP\001ZBgoogle." +
      "golang.org/genproto/googleapis/ads/googl" +
      "eads/v5/enums;enums\242\002\003GAA\252\002\035Google.Ads.G" +
      "oogleAds.V5.Enums\312\002\035Google\\Ads\\GoogleAds" +
      "\\V5\\Enums\352\002!Google::Ads::GoogleAds::V5::" +
      "Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v5_enums_OptimizationGoalTypeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v5_enums_OptimizationGoalTypeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v5_enums_OptimizationGoalTypeEnum_descriptor,
        new java.lang.String[] { });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
