// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v19/services/recommendation_service.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v19.services;

public interface GenerateRecommendationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v19.services.GenerateRecommendationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of generated recommendations from the passed in set of requested
   * recommendation_types. If there isn't sufficient data to generate a
   * recommendation for the requested recommendation_types, the result set won't
   * contain a recommendation for that type.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v19.resources.Recommendation recommendations = 1;</code>
   */
  java.util.List<com.google.ads.googleads.v19.resources.Recommendation> 
      getRecommendationsList();
  /**
   * <pre>
   * List of generated recommendations from the passed in set of requested
   * recommendation_types. If there isn't sufficient data to generate a
   * recommendation for the requested recommendation_types, the result set won't
   * contain a recommendation for that type.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v19.resources.Recommendation recommendations = 1;</code>
   */
  com.google.ads.googleads.v19.resources.Recommendation getRecommendations(int index);
  /**
   * <pre>
   * List of generated recommendations from the passed in set of requested
   * recommendation_types. If there isn't sufficient data to generate a
   * recommendation for the requested recommendation_types, the result set won't
   * contain a recommendation for that type.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v19.resources.Recommendation recommendations = 1;</code>
   */
  int getRecommendationsCount();
  /**
   * <pre>
   * List of generated recommendations from the passed in set of requested
   * recommendation_types. If there isn't sufficient data to generate a
   * recommendation for the requested recommendation_types, the result set won't
   * contain a recommendation for that type.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v19.resources.Recommendation recommendations = 1;</code>
   */
  java.util.List<? extends com.google.ads.googleads.v19.resources.RecommendationOrBuilder> 
      getRecommendationsOrBuilderList();
  /**
   * <pre>
   * List of generated recommendations from the passed in set of requested
   * recommendation_types. If there isn't sufficient data to generate a
   * recommendation for the requested recommendation_types, the result set won't
   * contain a recommendation for that type.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v19.resources.Recommendation recommendations = 1;</code>
   */
  com.google.ads.googleads.v19.resources.RecommendationOrBuilder getRecommendationsOrBuilder(
      int index);
}
