// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v1/enums/campaign_experiment_traffic_split_type.proto

package com.google.ads.googleads.v1.enums;

public interface CampaignExperimentTrafficSplitTypeEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v1.enums.CampaignExperimentTrafficSplitTypeEnum)
    com.google.protobuf.MessageOrBuilder {
}
