// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v1/enums/content_label_type.proto

package com.google.ads.googleads.v1.enums;

public interface ContentLabelTypeEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v1.enums.ContentLabelTypeEnum)
    com.google.protobuf.MessageOrBuilder {
}
