// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v9/enums/seasonality_event_scope.proto

package com.google.ads.googleads.v9.enums;

public final class SeasonalityEventScopeProto {
  private SeasonalityEventScopeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v9_enums_SeasonalityEventScopeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v9_enums_SeasonalityEventScopeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;google/ads/googleads/v9/enums/seasonal" +
      "ity_event_scope.proto\022\035google.ads.google" +
      "ads.v9.enums\032\034google/api/annotations.pro" +
      "to\"{\n\031SeasonalityEventScopeEnum\"^\n\025Seaso" +
      "nalityEventScope\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UNK" +
      "NOWN\020\001\022\014\n\010CUSTOMER\020\002\022\014\n\010CAMPAIGN\020\004\022\013\n\007CH" +
      "ANNEL\020\005B\357\001\n!com.google.ads.googleads.v9." +
      "enumsB\032SeasonalityEventScopeProtoP\001ZBgoo" +
      "gle.golang.org/genproto/googleapis/ads/g" +
      "oogleads/v9/enums;enums\242\002\003GAA\252\002\035Google.A" +
      "ds.GoogleAds.V9.Enums\312\002\035Google\\Ads\\Googl" +
      "eAds\\V9\\Enums\352\002!Google::Ads::GoogleAds::" +
      "V9::Enumsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_ads_googleads_v9_enums_SeasonalityEventScopeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v9_enums_SeasonalityEventScopeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v9_enums_SeasonalityEventScopeEnum_descriptor,
        new java.lang.String[] { });
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
