// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/ads/googleads/v23/common/ad_type_infos.proto
// Protobuf Java Version: 4.31.0

package com.google.ads.googleads.v23.common;

@com.google.protobuf.Generated
public interface TravelAdInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v23.common.TravelAdInfo)
    com.google.protobuf.MessageOrBuilder {
}
