// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/ads/googleads/v23/common/audiences.proto
// Protobuf Java Version: 4.31.0

package com.google.ads.googleads.v23.common;

@com.google.protobuf.Generated
public interface UserInterestSegmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v23.common.UserInterestSegment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The user interest resource.
   * </pre>
   *
   * <code>optional string user_interest_category = 1;</code>
   * @return Whether the userInterestCategory field is set.
   */
  boolean hasUserInterestCategory();
  /**
   * <pre>
   * The user interest resource.
   * </pre>
   *
   * <code>optional string user_interest_category = 1;</code>
   * @return The userInterestCategory.
   */
  java.lang.String getUserInterestCategory();
  /**
   * <pre>
   * The user interest resource.
   * </pre>
   *
   * <code>optional string user_interest_category = 1;</code>
   * @return The bytes for userInterestCategory.
   */
  com.google.protobuf.ByteString
      getUserInterestCategoryBytes();
}
