// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v20/common/bidding.proto

// Protobuf Java Version: 3.25.7
package com.google.ads.googleads.v20.common;

public interface ManualCpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v20.common.ManualCpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether bids are to be enhanced based on conversion optimizer data.
   * </pre>
   *
   * <code>optional bool enhanced_cpc_enabled = 2;</code>
   * @return Whether the enhancedCpcEnabled field is set.
   */
  boolean hasEnhancedCpcEnabled();
  /**
   * <pre>
   * Whether bids are to be enhanced based on conversion optimizer data.
   * </pre>
   *
   * <code>optional bool enhanced_cpc_enabled = 2;</code>
   * @return The enhancedCpcEnabled.
   */
  boolean getEnhancedCpcEnabled();
}
