// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v0/enums/month_of_year.proto

package com.google.ads.googleads.v0.enums;

public final class MonthOfYearProto {
  private MonthOfYearProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v0_enums_MonthOfYearEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v0_enums_MonthOfYearEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1google/ads/googleads/v0/enums/month_of" +
      "_year.proto\022\035google.ads.googleads.v0.enu" +
      "ms\"\321\001\n\017MonthOfYearEnum\"\275\001\n\013MonthOfYear\022\017" +
      "\n\013UNSPECIFIED\020\000\022\013\n\007UNKNOWN\020\001\022\013\n\007JANUARY\020" +
      "\002\022\014\n\010FEBRUARY\020\003\022\t\n\005MARCH\020\004\022\t\n\005APRIL\020\005\022\007\n" +
      "\003MAY\020\006\022\010\n\004JUNE\020\007\022\010\n\004JULY\020\010\022\n\n\006AUGUST\020\t\022\r" +
      "\n\tSEPTEMBER\020\n\022\013\n\007OCTOBER\020\013\022\014\n\010NOVEMBER\020\014" +
      "\022\014\n\010DECEMBER\020\rB\301\001\n!com.google.ads.google" +
      "ads.v0.enumsB\020MonthOfYearProtoP\001ZBgoogle" +
      ".golang.org/genproto/googleapis/ads/goog" +
      "leads/v0/enums;enums\242\002\003GAA\252\002\035Google.Ads." +
      "GoogleAds.V0.Enums\312\002\035Google\\Ads\\GoogleAd" +
      "s\\V0\\Enumsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_ads_googleads_v0_enums_MonthOfYearEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v0_enums_MonthOfYearEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v0_enums_MonthOfYearEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
