// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v0/enums/user_list_size_range.proto

package com.google.ads.googleads.v0.enums;

public final class UserListSizeRangeProto {
  private UserListSizeRangeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_ads_googleads_v0_enums_UserListSizeRangeEnum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_ads_googleads_v0_enums_UserListSizeRangeEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8google/ads/googleads/v0/enums/user_lis" +
      "t_size_range.proto\022\035google.ads.googleads" +
      ".v0.enums\"\224\005\n\025UserListSizeRangeEnum\"\372\004\n\021" +
      "UserListSizeRange\022\017\n\013UNSPECIFIED\020\000\022\013\n\007UN" +
      "KNOWN\020\001\022\032\n\026LESS_THAN_FIVE_HUNDRED\020\002\022\032\n\026L" +
      "ESS_THAN_ONE_THOUSAND\020\003\022 \n\034ONE_THOUSAND_" +
      "TO_TEN_THOUSAND\020\004\022\"\n\036TEN_THOUSAND_TO_FIF" +
      "TY_THOUSAND\020\005\022*\n&FIFTY_THOUSAND_TO_ONE_H" +
      "UNDRED_THOUSAND\020\006\0222\n.ONE_HUNDRED_THOUSAN" +
      "D_TO_THREE_HUNDRED_THOUSAND\020\007\0223\n/THREE_H" +
      "UNDRED_THOUSAND_TO_FIVE_HUNDRED_THOUSAND" +
      "\020\010\022(\n$FIVE_HUNDRED_THOUSAND_TO_ONE_MILLI" +
      "ON\020\t\022\036\n\032ONE_MILLION_TO_TWO_MILLION\020\n\022 \n\034" +
      "TWO_MILLION_TO_THREE_MILLION\020\013\022!\n\035THREE_" +
      "MILLION_TO_FIVE_MILLION\020\014\022\037\n\033FIVE_MILLIO" +
      "N_TO_TEN_MILLION\020\r\022!\n\035TEN_MILLION_TO_TWE" +
      "NTY_MILLION\020\016\022$\n TWENTY_MILLION_TO_THIRT" +
      "Y_MILLION\020\017\022#\n\037THIRTY_MILLION_TO_FIFTY_M" +
      "ILLION\020\020\022\026\n\022OVER_FIFTY_MILLION\020\021B\353\001\n!com" +
      ".google.ads.googleads.v0.enumsB\026UserList" +
      "SizeRangeProtoP\001ZBgoogle.golang.org/genp" +
      "roto/googleapis/ads/googleads/v0/enums;e" +
      "nums\242\002\003GAA\252\002\035Google.Ads.GoogleAds.V0.Enu" +
      "ms\312\002\035Google\\Ads\\GoogleAds\\V0\\Enums\352\002!Goo" +
      "gle::Ads::GoogleAds::V0::Enumsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_ads_googleads_v0_enums_UserListSizeRangeEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_ads_googleads_v0_enums_UserListSizeRangeEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_ads_googleads_v0_enums_UserListSizeRangeEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
