// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v3/errors/feed_item_target_error.proto

package com.google.ads.googleads.v3.errors;

public interface FeedItemTargetErrorEnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v3.errors.FeedItemTargetErrorEnum)
    com.google.protobuf.MessageOrBuilder {
}
