// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/ads/googleads/v10/services/geo_target_constant_service.proto

package com.google.ads.googleads.v10.services;

public interface SuggestGeoTargetConstantsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.ads.googleads.v10.services.SuggestGeoTargetConstantsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Geo target constant suggestions.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v10.services.GeoTargetConstantSuggestion geo_target_constant_suggestions = 1;</code>
   */
  java.util.List<com.google.ads.googleads.v10.services.GeoTargetConstantSuggestion> 
      getGeoTargetConstantSuggestionsList();
  /**
   * <pre>
   * Geo target constant suggestions.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v10.services.GeoTargetConstantSuggestion geo_target_constant_suggestions = 1;</code>
   */
  com.google.ads.googleads.v10.services.GeoTargetConstantSuggestion getGeoTargetConstantSuggestions(int index);
  /**
   * <pre>
   * Geo target constant suggestions.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v10.services.GeoTargetConstantSuggestion geo_target_constant_suggestions = 1;</code>
   */
  int getGeoTargetConstantSuggestionsCount();
  /**
   * <pre>
   * Geo target constant suggestions.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v10.services.GeoTargetConstantSuggestion geo_target_constant_suggestions = 1;</code>
   */
  java.util.List<? extends com.google.ads.googleads.v10.services.GeoTargetConstantSuggestionOrBuilder> 
      getGeoTargetConstantSuggestionsOrBuilderList();
  /**
   * <pre>
   * Geo target constant suggestions.
   * </pre>
   *
   * <code>repeated .google.ads.googleads.v10.services.GeoTargetConstantSuggestion geo_target_constant_suggestions = 1;</code>
   */
  com.google.ads.googleads.v10.services.GeoTargetConstantSuggestionOrBuilder getGeoTargetConstantSuggestionsOrBuilder(
      int index);
}
